services:
  - type: web
    name: attendease-backend
    env: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: attendance_system
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: JWT_SECRET
        generateValue: true
